fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "oscarmateo1997@gmail.com"
        sender_name: "Oscar Mateo @the97prime"
        
    registration:
        confirmation:
            enabled: true